# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - PHPDocSpark

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm dependencies and build assets
        run: |
          cd website
          npm ci
          npm run build

      - name: Check if composer.json exists and run composer install
        working-directory: website
        run: |
          if [ -f "composer.json" ]; then
            echo "composer.json exists, running composer commands..."
            composer validate --no-check-publish && composer install --prefer-dist --no-progress
          else
            echo "composer.json not found, skipping composer install"
          fi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: website/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BC32B217E6394E84999918FCF6835B23 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6EA193E9B6A04E439F12D66662B87A41 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0CADF42789EC4536930A4B252963F12C }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'PHPDocSpark'
          slot-name: 'Production'
          package: .
